extends: airbnb/base
plugins:
  - mocha
globals:
  describe: true
  it: true
  beforeEach: true
  afterEach: true
  Promise: true
rules:
  import/no-extraneous-dependencies: 0


  max-len:
    - error
    - 120
    - ignoreComments: true
    - ignoreUrls: true
  vars-on-top: 0
  padded-blocks: 0
  func-names: 0

  no-prototype-builtins: 0
  no-lonely-if: 0

  consistent-return: 0
  no-param-reassign: 0
  no-underscore-dangle: 0
  prefer-template: 0
  comma-dangle: 0
