extends: airbnb/base
plugins:
  - mocha
globals:
  describe: true
  it: true
  beforeEach: true
  afterEach: true
  Promise: true
rules:
  import/no-extraneous-dependencies: 0
  class-methods-use-this: 0
  max-len: 0
  consistent-return: 0
  no-param-reassign: 0
  no-underscore-dangle: 0
  prefer-template: 0
  comma-dangle: 0
  arrow-body-style: 0
